config/routes.rb
Rails.application.routes.draw do
  get 'counsels/list_counsel_index'

  resources :counsels
  resources :counselings
  resources :healths

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :questions
  resources :answers
  get 'home/top'

  get 'infection/top'
  get 'absences/index'


  resources :users

  root 'home#top' # トップページをhomeコントローラのindexアクションに設定
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  validate :error_check

    def error_check
        if answer.blank?
            errors[:base]<< '回答を入力してください'
        end
    end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counsel.rb
class Counsel < ApplicationRecord
  has_many :counselings
end

app/models/counseling.rb
class Counseling < ApplicationRecord
  belongs_to :hour
  belongs_to :user
  belongs_to :counsel
end

app/models/health.rb
class Health < ApplicationRecord
    belongs_to :symptom
    belongs_to :user
end

app/models/hour.rb
class Hour < ApplicationRecord
  has_many :counselings
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers
    belongs_to :user
    
    validate :error_check

    def error_check
        if question.blank?
            errors[:base]<< '質問を入力しよう'
        end
    end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
    has_many :healths
end

app/models/user.rb
class User < ApplicationRecord
    has_many :questions
    has_many :answers
    has_many :healths
    has_many :counselings

    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @today = Date.today
    week = ['日','月','火','水','木','金','土']
    @yobi = week[@today.wday]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.left_joins(:answers).group(:id).select("questions.*, count(answers.id) AS answer_count").where(user_id: current_user.id).order('created_at DESC')
    .limit(30)
    @question = Question.new(user_id: current_user.id)
    @question.errors.clear
   
    # .select("questions.*, answers.answer, answers.created_at answer_date").where(user_id: current_user.id)
    
    
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @questions = Question.find(params[:id])
    @answers = Answer.where(question_id: params[:id])
  end

  # GET /questions/new
  def new
  end

  # GET /questions/1/edit
  def edit

  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(user_id: current_user.id, question: params[:question])
    @questions = Question.left_joins(:answers).group(:id).select("questions.*, count(answers.id) AS answer_count").where(user_id: current_user.id).order('created_at DESC')

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path }
        #format.json { render :index, status: :created, location: @question }
      else
        format.html { render :index }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:user_id, :question)

    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:account, :password, :grade, :class, :number, :name, :graduate, :teacher)
    end
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counseling_helper.rb
module CounselingHelper
end

app/helpers/counsels_helper.rb
module CounselsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infection_helper.rb
module InfectionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    #ログイン処理
    def log_in(user)
        session[:user_id] = user.id
    end

    #現在ログインしているユーザを返す
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    #ログインしているかを返す
    def logged_in?
        !current_user.nil?
    end

    #ログアウト処理
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  



  <div class="field">
    <%= form.label :質問 %>
    <%= form.text_field :question, id: :question_question %>
  </div>

  <div class="actions">
    <%= form.submit :変更 %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1 align="center">編集</h1>

<%= render 'form', question: @question %>

<%= link_to '詳細', @question %> |
<%= link_to '戻る', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align= "center">Q&A</h1>
<div id="q_table">
  <table border="1">
    <thead>
      <tr>
        <th width="29%">日時</th>
        <th width="55%">質問内容</th>
        <th width="10%">回答件数</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td><%= question.created_at.strftime("%Y年%-m月%-d日 %-H時%-M分") %></td>
          <td><%= safe_join(question.question.split("\n"),tag(:br)) %></td>
          <td align="center"><%= question.answer_count %></td>
          <td  align="center"><%= link_to '詳細', question %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= form_with(url: '/questions', local: true) do |form| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "") %> 個のエラーで送信できません</h2>
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% form.label :question %>
    <%= form.text_area :question, id: :question_question, :size=>"50x8"%>
  </div>

  <div class="actions">
    <%= submit_tag "送信" %>
  </div>
<% end %>

<%= link_to 'TOPページに戻る', home_top_path %>

app/views/questions/new.html.erb
<h1>追加</h1>

<%= render 'form', question: @question %>

<%= link_to '戻る', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<table class="show">
  <thead>
    <tr>
      <th width="3%">年</th>
      <th width="3%">組</th>
      <th width="3%">番</th>
      <th width="10%">氏名</th>
      <th width="15%">質問内容</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @questions.user.grade %></td>
      <td><%= @questions.user.room %></td>
      <td><%= @questions.user.number %></td>
      <td><%= @questions.user.name %></td>
      <td><%= safe_join(@questions.question.split("\n"),tag(:br)) %></td>
    </tr>
  </tbody>
</table>

<div class="answer_center">
  <% @answers.each do |answer| %>
    <div class="answer">
      <b>回答内容</b>
      <p><%= answer.answer %></p>
    </div>
  <% end %>
</div>

<%= link_to '編集', edit_question_path(@question) %> |
<%= link_to '戻る', questions_path %>