config/routes.rb
Rails.application.routes.draw do
  get 'counsels/list_counsel_index'

  resources :counsels
  resources :counselings
  resources :healths

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :questions
  resources :answers
  get 'home/top'

  get 'infection/top'
  get 'absences/index'


  resources :users

  root 'home#top' # トップページをhomeコントローラのindexアクションに設定
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  validate :error_check

    def error_check
        if answer.blank?
            errors[:base]<< '回答を入力してください'
        end
    end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counsel.rb
class Counsel < ApplicationRecord
  has_many :counselings
end

app/models/counseling.rb
class Counseling < ApplicationRecord
  belongs_to :hour
  belongs_to :user
  belongs_to :counsel
end

app/models/health.rb
class Health < ApplicationRecord
    belongs_to :symptom
    belongs_to :user
end

app/models/hour.rb
class Hour < ApplicationRecord
  has_many :counselings
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers
    belongs_to :user
    
    validate :error_check

    def error_check
        if question.blank?
            errors[:base]<< '質問を入力しよう'
        end
    end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
    has_many :healths
end

app/models/user.rb
class User < ApplicationRecord
    has_many :questions
    has_many :answers
    has_many :healths
    has_many :counselings

    
end

app/controllers/counsels_controller.rb
class CounselsController < ApplicationController
  before_action :set_counsel, only: [:show, :edit, :update, :destroy]

  def list_counsel_index
    @counselings = Counseling.all
    @today = Date.today
  end

  # GET /counsels
  # GET /counsels.json
  def index
    @counsels = Counsel.all
    @today = Date.today
  end

  # GET /counsels/1
  # GET /counsels/1.json
  def show
  end

  # GET /counsels/new
  def new
    @counsel = Counsel.new
  end

  # GET /counsels/1/edit
  def edit
  end

  # POST /counsels
  # POST /counsels.json
  def create
    @counsel = Counsel.new(counsel_params)

    respond_to do |format|
      if @counsel.save
        format.html { redirect_to @counsel, notice: 'Counsel was successfully created.' }
        format.json { render :show, status: :created, location: @counsel }
      else
        format.html { render :new }
        format.json { render json: @counsel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counsels/1
  # PATCH/PUT /counsels/1.json
  def update
    respond_to do |format|
      if @counsel.update(counsel_params)
        format.html { redirect_to @counsel, notice: 'Counsel was successfully updated.' }
        format.json { render :show, status: :ok, location: @counsel }
      else
        format.html { render :edit }
        format.json { render json: @counsel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counsels/1
  # DELETE /counsels/1.json
  def destroy
    @counsel.destroy
    respond_to do |format|
      format.html { redirect_to counsels_url, notice: 'Counsel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counsel
      @counsel = Counsel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def counsel_params
      params.require(:counsel).permit(:day, :start_time, :end_time, :teacher)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @today = Date.today
    week = ['日','月','火','水','木','金','土']
    @yobi = week[@today.wday]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:account, :password, :grade, :class, :number, :name, :graduate, :teacher)
    end
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counseling_helper.rb
module CounselingHelper
end

app/helpers/counsels_helper.rb
module CounselsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infection_helper.rb
module InfectionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    #ログイン処理
    def log_in(user)
        session[:user_id] = user.id
    end

    #現在ログインしているユーザを返す
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    #ログインしているかを返す
    def logged_in?
        !current_user.nil?
    end

    #ログアウト処理
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/counsels/_form.html.erb
<%= form_with(model: counsel, local: true) do |form| %>
  <% if counsel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(counsel.errors.count, "error") %> prohibited this counsel from being saved:</h2>

      <ul>
      <% counsel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-counsel">
    <div class="field">
      <%= form.label :日にち %>
      <%= form.date_select :day, id: :counsel_day %>
    </div>

    <div class="field">
      <%= form.label :開始時間 %>
      <%= form.number_field :start_time, id: :counsel_start_time %>
    </div>

    <div class="field">
      <%= form.label :終了時間 %>
      <%= form.number_field :end_time, id: :counsel_end_time %>
    </div>

    <div class="field">
      <%= form.label :先生 %>
      <%= form.text_field :teacher, id: :counsel_teacher %>
    </div>

    <div class="actions">
      <%= form.submit "OK" %>
    </div>
  </div>
<% end %>

app/views/counsels/edit.html.erb
<h1>編集</h1>

<%= render 'form', counsel: @counsel %>

<%= link_to '詳細', @counsel %> |
<%= link_to '戻る', counsels_path %>

app/views/counsels/index.html.erb
<% require "date" %>
<p id="not""ice"><%= notice %></p>

<h1>カウンセリング一覧</h1>

<table border="1">
  <thead>
    <tr>
      <th>日にち</th>
      <th>時間</th>
      <th>先生</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counsels.each do |counsel| %>
      <% if counsel.day > @today %>
        <tr>
          <td><%= counsel.day %></td>
          <td><%= counsel.start_time.strftime("%H:%M") %>~<%= counsel.end_time.strftime("%H:%M") %></td>
          <td><%= counsel.teacher %>先生</td>
          <td><%= link_to '詳細', counsel %></td>
          <td><%= link_to '編集', edit_counsel_path(counsel) %></td>
          <td><%= link_to '削除', counsel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '申し込み者一覧', '/counsels/list_counsel_index/' %> |
<%= link_to '追加', new_counsel_path %>

<br>

<%= link_to 'TOPページに戻る', home_top_path %>

app/views/counsels/list_counsel_index.html.erb
<% require "date" %>
<p id="not""ice"><%= notice %></p>

<h1>カウンセリング申し込み者一覧</h1>

<table border="1">
  <thead>
    <tr>
      <th>日にち</th>
      <th>時間</th>
      <th>先生</th>
      <th>年</th>
      <th>組</th>
      <th>番</th>
      <th>氏名</th>
    </tr>
  </thead>

  <tbody>
    <% @counselings.each do |counseling| %>
      <% if counseling.counsel.day > @today %>
        <tr>
          <td><%= counseling.counsel.day %></td>
          <td><%= counseling.hour.display %></td>
          <td><%= counseling.counsel.teacher %>先生</td>
          <td><%= counseling.user.grade %></td>
          <td><%= counseling.user.room %></td>
          <td><%= counseling.user.number %></td>
          <td><%= counseling.user.name %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '戻る', counsels_path %>

app/views/counsels/new.html.erb
<h1>追加</h1>

<%= render 'form', counsel: @counsel %>

<%= link_to '戻る', counsels_path %>

app/views/counsels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>日にち:</strong>
  <%= @counsel.day %>
</p>

<p>
  <strong>開始時間:</strong>
  <%= @counsel.start_time.strftime("%H:%M") %>
</p>

<p>
  <strong>終了時間:</strong>
  <%= @counsel.end_time.strftime("%H:%M") %>
</p>

<p>
  <strong>先生:</strong>
  <%= @counsel.teacher %>先生
</p>

<%= link_to '編集', edit_counsel_path(@counsel) %> |
<%= link_to '戻る', counsels_path %>