config/routes.rb
Rails.application.routes.draw do
  get 'counsels/list_counsel_index'

  resources :counsels
  resources :counselings
  resources :healths

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :questions
  resources :answers
  get 'home/top'

  get 'infection/top'
  get 'absences/index'


  resources :users

  root 'home#top' # トップページをhomeコントローラのindexアクションに設定
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  validate :error_check

    def error_check
        if answer.blank?
            errors[:base]<< '回答を入力してください'
        end
    end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counsel.rb
class Counsel < ApplicationRecord
  has_many :counselings
end

app/models/counseling.rb
class Counseling < ApplicationRecord
  belongs_to :hour
  belongs_to :user
  belongs_to :counsel
end

app/models/health.rb
class Health < ApplicationRecord
    belongs_to :symptom
    belongs_to :user
end

app/models/hour.rb
class Hour < ApplicationRecord
  has_many :counselings
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers
    belongs_to :user
    
    validate :error_check

    def error_check
        if question.blank?
            errors[:base]<< '質問を入力しよう'
        end
    end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
    has_many :healths
end

app/models/user.rb
class User < ApplicationRecord
    has_many :questions
    has_many :answers
    has_many :healths
    has_many :counselings

    
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  before_action :set_health, only: [:show, :edit, :update, :destroy]

  # GET /healths
  # GET /healths.json
  def index
    @userclasss = [[1,1],[1,2],[1,3],[1,4],[2,1],[2,2],[2,3],[2,4],[3,1],[3,2],[3,3],[3,4]]
    @healths = Health.where.not(symptom_id: 58)
    @today = Date.today
    @healthdays = Health.select(:day).distinct.order(:day)
    
    @userclasss.each do |userclass|
      @absenceusers = []
      @absenceclass = []
      userclass << []
      userclass << []
      @absence = []
      users = User.all
      @healthdays.each do |healthday|
        @absencecount = 0
        @absenceclasscount = 0
        if healthday.day.wday != 0 or healthday.day.wday != 6
          @absenceusers = []
          @absenceclass = []
          users.each do |user|
            if user.teacher == FALSE and Health.where(day: healthday.day).where(user_id: user.id).empty? then
              @absenceusers << user
              @absencecount = @absencecount + 1
            end
          end
          @absenceusers.each do |absenceuser|
            if absenceuser.grade == userclass[0] and absenceuser.room == userclass[1]
              userclass[2] = absenceuser
              @absenceclasscount = @absenceclasscount + 1
              userclass[3] << [healthday.day, @absenceclasscount]
            end
          end
          @absence << [healthday.day, @absencecount]
        end
      end
  
      @symptoms = []
      userclass << []
      userclass << []
      @healths.each do |health|
        @symptoms << health
        @symptomcount = Health.where.not(symptom_id: 58).group(:day).count
        if health.user.grade == userclass[0] and health.user.room == userclass[1]
          userclass[4] = health
          userclass[5] = Health.where.not(symptom_id: 58).group(:day).count
        end
      end
    end
  end

  # GET /healths/1
  # GET /healths/1.json
  def show
  end

  # GET /healths/new
  def new
    @health = Health.new
    @date = Date.today
  end

  # GET /healths/1/edit
  def edit
  end

  # POST /healths
  # POST /healths.json
  def create
    @health = Health.new(health_params)
    @health.user_id = current_user.id

    respond_to do |format|
      if @health.save
        format.html { redirect_to @health}
        format.json { render :show, status: :created, location: @health }
      else
        format.html { render :new }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /healths/1
  # PATCH/PUT /healths/1.json
  def update
    respond_to do |format|
      if @health.update(health_params)
        format.html { redirect_to @health }
        format.json { render :show, status: :ok, location: @health }
      else
        format.html { render :edit }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /healths/1
  # DELETE /healths/1.json
  def destroy
    @health.destroy
    respond_to do |format|
      format.html { redirect_to healths_url, notice: 'Health was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health
      @health = Health.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def health_params
      params.require(:health).permit(:user_id, :temperature, :condition, :symptom_id, :day)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @today = Date.today
    week = ['日','月','火','水','木','金','土']
    @yobi = week[@today.wday]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:account, :password, :grade, :class, :number, :name, :graduate, :teacher)
    end
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counseling_helper.rb
module CounselingHelper
end

app/helpers/counsels_helper.rb
module CounselsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infection_helper.rb
module InfectionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    #ログイン処理
    def log_in(user)
        session[:user_id] = user.id
    end

    #現在ログインしているユーザを返す
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    #ログインしているかを返す
    def logged_in?
        !current_user.nil?
    end

    #ログアウト処理
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/healths/_form.html.erb
<%= form_with(model: health, local: true) do |form| %>
  <% if health.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health.errors.count, "error") %> prohibited this health from being saved:</h2>

      <ul>
      <% health.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-health">
    <div class="field">
      <%= form.label :体温 %>
      <p><%= form.number_field :temperature, step: "0.1", id: :health_temperature %>℃</p>
    </div>

    <div class="field">
      <%= form.label :体調 %>
      <label><%= form.radio_button :condition, "良い" %>良い</label>
      <label><%= form.radio_button :condition, "悪い" %>悪い</label>
    </div>

    <div class="field">
      <%= form.label :症状 %>
      <%= form.collection_select :symptom_id, Symptom.all, :id, :display %>
    </div>

    <div class="field">
      <%= form.hidden_field :day, :value => @date %>
    </div>

    <div class="actions">
      <%= form.submit :送信 %>
    </div>
  </div>
<% end %>

app/views/healths/edit.html.erb
<h1>健康観察</h1>

<%= render 'form', health: @health %>

<%= link_to '詳細', @health %> |
<%= link_to '戻る', healths_path %>

app/views/healths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>欠席者・症状別一覧</h1>

<table>
  <tr>
    <td><h3 id="absenceall">欠席者一覧</h3></td>
    <div>
      <td>
        <div id="absencedata">
          <table border="1">
             <tr>
               <th>年</th>
               <th>組</th>
               <th>番</th>
               <th>氏名</th>
             </tr>
            <% @absenceusers.each do |absenceuser| %>
              <% @absence.each do |absence| %>
                <% if absence[0] == @today %>
                  <tr>
                    <td><%= absenceuser.grade %></td>
                    <td><%= absenceuser.room %></td>
                    <td><%= absenceuser.number %></td>
                    <td><%= absenceuser.name %></td>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          </table>
        </div>
     </td>
     <td>
       <div id="absencechart">
         <%= column_chart @absence %>
       </div>
     </td>
    </div>
    <script>
      $('#absencedata').hide();
      $('#absencechart').hide();
      $(function () {
        $('#absenceall').click(function () {
            $('#absencedata').toggle();
            $('#absencechart').toggle();
        });
      });
    </script>
  </tr>
 

  <% @userclasss.each do |userclass| %>
    <tr>
      <td><h4 id=<%= "absence#{userclass[0]}#{userclass[1]}"%>><%= "#{userclass[0]}年#{userclass[1]}組" %></h4></td>
      <div>
        <td>
          <div id=<%= "absencedata#{userclass[0]}#{userclass[1]}"%>>
            <table border="1">
              <tr>
                <th>年</th>
                <th>組</th>
                <th>番</th>
                <th>氏名</th>
              </tr>
              <% if userclass[2].present? %>
                <% if userclass[4].day == @today %>
                  <tr>
                    <td><%= userclass[2].grade %></td>
                    <td><%= userclass[2].room %></td>
                    <td><%= userclass[2].number %></td>
                    <td><%= userclass[2].name %></td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
        </td>
        <td>
          <div id=<%= "absencechart#{userclass[0]}#{userclass[1]}"%>>
            <%= column_chart userclass[3] %>
          </div>
        </td>
      </div>
      <script>
      $('#<%= "absencedata#{userclass[0]}#{userclass[1]}"%>').hide();
      $('#<%= "absencechart#{userclass[0]}#{userclass[1]}"%>').hide();
      $(function () {
        $('#<%= "absence#{userclass[0]}#{userclass[1]}"%>').click(function () {
            $('#<%= "absencedata#{userclass[0]}#{userclass[1]}"%>').toggle();
            $('#<%= "absencechart#{userclass[0]}#{userclass[1]}"%>').toggle();
        });
      });
    </script>
    </tr>
  <% end %>


  <tr>
    <td><h3 id="symptomall">症状別一覧</h3></td>
    <div>
      <td>
        <div id="symptomdata">
          <table border="1">
            <tr>
              <th>年</th>
              <th>組</th>
              <th>番</th>
              <th>氏名</th>
              <th>体温</th>
              <th>体調</th>
              <th>症状</th>
            </tr>

            <% @symptoms.each do |symptom| %>
              <% if symptom.day == @today %>
                <tr>
                  <td><%= symptom.user.grade %></td>
                  <td><%= symptom.user.room %></td>
                  <td><%= symptom.user.number %></td>
                  <td><%= symptom.user.name %></td>
                  <td><%= symptom.temperature %></td>
                  <td><%= symptom.condition %></td>
                  <td><%= symptom.symptom.display %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
        </div>
      </td>
      <td>
        <div id="symptomchart">
          <%= column_chart @symptomcount %>
        </div>
      </td>
    </div>
    <script>
    $('#symptomdata').hide();
    $('#symptomchart').hide();
    $(function () {
      $('#symptomall').click(function () {
          $('#symptomdata').toggle();
          $('#symptomchart').toggle();
      });
    });
  </script>
  </tr>
  
  <% @userclasss.each do |userclass| %>
    <tr>
      <td><h4 id=<%= "symptom#{userclass[0]}#{userclass[1]}"%>><%= "#{userclass[0]}年#{userclass[1]}組" %></h4></td>
      <div>
        <td>
          <div id=<%= "symptomdata#{userclass[0]}#{userclass[1]}"%>>
            <table border="1">
              <tr>
                <th>年</th>
                <th>組</th>
                <th>番</th>
                <th>氏名</th>
                <th>体温</th>
                <th>体調</th>  
                <th>症状</th>
              </tr>
              <% if userclass[4].present? %>
                <% if userclass[4].day == @today %>
                  <tr>
                    <td><%= userclass[4].user.grade %></td>
                    <td><%= userclass[4].user.room %></td>
                    <td><%= userclass[4].user.number %></td>
                    <td><%= userclass[4].user.name %></td>
                    <td><%= userclass[4].temperature %></td>
                    <td><%= userclass[4].condition %></td>
                    <td><%= userclass[4].symptom.display %></td>
                  </tr>
                <% end %>
              <% end %>
            </table>
          </div>
        </td>
        <td>
          <div id=<%= "symptomchart#{userclass[0]}#{userclass[1]}"%>>
            <%= column_chart userclass[5] %>
          </div>
        </td>
      </div>
      <script>
      $('#<%= "symptomdata#{userclass[0]}#{userclass[1]}"%>').hide();
      $('#<%= "symptomchart#{userclass[0]}#{userclass[1]}"%>').hide();
      $(function () {
        $('#<%= "symptom#{userclass[0]}#{userclass[1]}"%>').click(function () {
            $('#<%= "symptomdata#{userclass[0]}#{userclass[1]}"%>').toggle();
            $('#<%= "symptomchart#{userclass[0]}#{userclass[1]}"%>').toggle();
        });
      });
    </script>
    </tr>
  <% end %>
</table>

<%= link_to 'TOPページに戻る', home_top_path %>

app/views/healths/new.html.erb
<h1>健康観察</h1>

<%= render 'form', health: @health %>

<%= link_to 'TOPページに戻る', home_top_path %>

app/views/healths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>体温:</strong>
  <%= @health.temperature %>℃
</p>

<p>
  <strong>体調:</strong>
  <%= @health.condition %>
</p>

<p>
  <strong>症状:</strong>
  <%= @health.symptom.display %>
</p>

<%= link_to 'TOPページに戻る', home_top_path %>