config/routes.rb
Rails.application.routes.draw do
  get 'counsels/list_counsel_index'

  resources :counsels
  resources :counselings
  resources :healths

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  resources :questions
  resources :answers
  get 'home/top'

  get 'infection/top'
  get 'absences/index'


  resources :users

  root 'home#top' # トップページをhomeコントローラのindexアクションに設定
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  validate :error_check

    def error_check
        if answer.blank?
            errors[:base]<< '回答を入力してください'
        end
    end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counsel.rb
class Counsel < ApplicationRecord
  has_many :counselings
end

app/models/counseling.rb
class Counseling < ApplicationRecord
  belongs_to :hour
  belongs_to :user
  belongs_to :counsel
end

app/models/health.rb
class Health < ApplicationRecord
    belongs_to :symptom
    belongs_to :user
end

app/models/hour.rb
class Hour < ApplicationRecord
  has_many :counselings
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers
    belongs_to :user
    
    validate :error_check

    def error_check
        if question.blank?
            errors[:base]<< '質問を入力しよう'
        end
    end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
    has_many :healths
end

app/models/user.rb
class User < ApplicationRecord
    has_many :questions
    has_many :answers
    has_many :healths
    has_many :counselings

    
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @questions = Question.left_joins(:answers).group(:id).select("questions.*, count(answers.answer) AS answer_count").order('created_at DESC').limit(50)
    @answer = Answer.new
  end
  
  def new
    @questions = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    @questions = Question.find(params[:answer][:question_id])

    respond_to do |format|
      if @answer.save
         format.html{ redirect_to answers_path }
      else
        format.html{ render :new }
      end
    end
  end
    
    
     
    
  

  private
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:question_id, :user_id, :answer)

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @today = Date.today
    week = ['日','月','火','水','木','金','土']
    @yobi = week[@today.wday]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:account, :password, :grade, :class, :number, :name, :graduate, :teacher)
    end
end

app/helpers/absences_helper.rb
module AbsencesHelper
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counseling_helper.rb
module CounselingHelper
end

app/helpers/counsels_helper.rb
module CounselsHelper
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infection_helper.rb
module InfectionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    #ログイン処理
    def log_in(user)
        session[:user_id] = user.id
    end

    #現在ログインしているユーザを返す
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    #ログインしているかを返す
    def logged_in?
        !current_user.nil?
    end

    #ログアウト処理
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :answer_user_id %>
  </div>

  <div class="field">
    <%= form.label :answer %>
    <%= form.text_field :answer, id: :answer_answer %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>質問者一覧</h1>
<div id="a_table">
  <table border="1">
    <thead>
      <tr>
        <th>年</th>
        <th>組</th>
        <th>番</th>
        <th width= "15%">氏名</th>
        <th width= "55%">質問内容<th>
        <th width= "8%">回答数</th>
      </tr>
    </thead>

    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td><%= question.user.grade %></td>
          <td><%= question.user.room %></td>
          <td><%= question.user.number %></td>
          <td><%= question.user.name %></td>
          <td><%= safe_join(question.question.split("\n"),tag(:br)) %></td>
          <td width="8%"><%= link_to '選択', new_answer_path(question_id: question.id) %></td>
          <td><%= question.answer_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'TOPページに戻る', home_top_path %>

app/views/answers/new.html.erb
<h1>回答</h1>

<table class="answer_margin">
  <thead>
    <tr>
      <th>年</th>
      <th>組</th>
      <th>番</th>
      <th width="15%">氏名</th>
      <th width="80%">質問内容</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @questions.user.grade %></td>
      <td><%= @questions.user.room %></td>
      <td><%= @questions.user.number %></td>
      <td><%= @questions.user.name %></td>
      <td><%= safe_join(@questions.question.split("\n"),tag(:br)) %></td>
    </tr>
  </tbody>
</table>

<br>

<%= form_with model:@answer, local: true do |form| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "") %> 個のエラーで送信できません</h2>
      <ul>
        <% @answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :question_id, :value => @questions.id %>
  <%= form.hidden_field :user_id, :value => @questions.user_id %>

  <div class="field">
    <% form.label :answer %>
    <%= form.text_area :answer, id: :answer_answer, :size=>"50x8" %>
  </div>

  <div class="actions">
    <%= submit_tag "送信" %>
  </div>
<% end %>

<%= link_to '戻る', answers_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account %>
    <%= form.text_field :account, id: :user_account %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.number_field :grade, id: :user_grade %>
  </div>

  <div class="field">
    <%= form.label :class %>
    <%= form.number_field :class, id: :user_class %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :user_number %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :graduate %>
    <%= form.check_box :graduate, id: :user_graduate %>
  </div>

  <div class="field">
    <%= form.label :teacher %>
    <%= form.check_box :teacher, id: :user_teacher %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Password</th>
      <th>Grade</th>
      <th>Class</th>
      <th>Number</th>
      <th>Name</th>
      <th>Graduate</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.account %></td>
        <td><%= user.password %></td>
        <td><%= user.grade %></td>
        <td><%= user.class %></td>
        <td><%= user.number %></td>
        <td><%= user.name %></td>
        <td><%= user.graduate %></td>
        <td><%= user.teacher %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @user.account %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @user.grade %>
</p>

<p>
  <strong>Class:</strong>
  <%= @user.class %>
</p>

<p>
  <strong>Number:</strong>
  <%= @user.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Graduate:</strong>
  <%= @user.graduate %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @user.teacher %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>